import { Inter } from "next/font/google";
import ThemeRegistry from "../theme/ThemeRegistry";
import Navbar from "@/components/Common/NavBar";
import Footer from "@/components/Common/Footer";
import MasterLayout from "@/components/Common/MasterLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body className={inter.className}>
          {" "}
          <MasterLayout>{children}</MasterLayout>
        </body>
      </ThemeRegistry>
    </html>
  );
}
